### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pierrotm777** [soligen2010/RC_RX_CABELL_V3_FHSS#6] opened 2018-12-18 06:43 UTC
Hello,
I try to compile your project with the 1.8.8 ide but i obtain an error .
C:\Users\pierre\AppData\Local\Temp\arduino_build_756723\sketch\RX.cpp: In function 'setFailSafeValues':

C:\Users\pierre\AppData\Local\Temp\arduino_build_756723\sketch\RX.cpp:650:1: internal compiler error: Segmentation fault

 }

 ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\tmp\Arduino_Compilateur\arduino-1.8.5\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/tmp/arduino_compilateur/arduino-1.8.5/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

Utilisation de la bibliothèque SPI version 1.0 dans le dossier: C:\tmp\Arduino_Compilateur\arduino-1.8.5\hardware\arduino\avr\libraries\SPI 
Utilisation de la bibliothèque EEPROM version 2.0 dans le dossier: C:\tmp\Arduino_Compilateur\arduino-1.8.5\hardware\arduino\avr\libraries\EEPROM 
exit status 1
Erreur de compilation pour la carte Arduino Pro or Pro Mini

Can you help me please ?

Thanks

**Comment by soligen2010** [comment] 2018-12-18 21:55
I upgraded to 1.8.8 and it compile fine for me, so it must be something wrong with your installation or settings.  

All I could suggest is to make sure you have the right board selected - I use the Arduino Nano board selection. It seems to work fine for the Pro Mini boards.

**Comment by krukhlis** [comment] 2018-12-18 22:07
There was a buggy version of Arduino recently released, tons of people have suffered from lto-wrapper error. Could be the same. In the most recent version they say they have fixed it:
http://forum.arduino.cc/index.php?topic=576749.0

**Comment by per1234** [comment] 2018-12-19 02:45
@krukhlis I think that is a different issue. This is the correct one:
https://github.com/arduino/Arduino/issues/7949

This bug is difficult to reproduce. It comes and goes for no apparent reason. I've also only seen it occur for people using Windows. So it's not surprising that it did not occur for @soligen2010.

I don't think the issue is caused in any way by the code in this library and I don't think any changes to this code could fix it (though they might make it disappear purely by chance).

There is a beta release of a new AVR toolchain that is intended to fix the bug. If you want to give it a try, you can install it by doing this:

1. File > Preferences
2. In the "Additional Boards Manager URLs" field, add http://downloads.arduino.cc/packages/package_avr_7.3.0_index.json
3. Click "OK".
4. Tools > Board > Boards Manager
5. Wait for downloads to finish.
6. Click on "Arduino AVR Boards".
7. Click "Update".
8. Wait for the update to finish.
9. Click "Close".
10. Try compiling again.

**Comment by pierrotm777** [comment] 2018-12-19 06:57
Thanks for your answer. I shall try to update my board definition.

**Comment by pierrotm777** [comment] 2018-12-19 07:29
Thanks for your help. That's curious, i can compile for uno or pro mini
when i don't upload the code. But wgen I try to upload, i can't. I have had
one success with an uno board. But never with my pro mini.
Sorry for my English.

**Comment by pierrotm777** [comment] 2018-12-19 10:53
I have tried to build a prototype based on a nrf24l01 without pa lna. I use
for my test a uno board with a converter level for moso, miso, sck ans csn.
Ce is connected to 3,3v. Irq with a 1n4148.
I use a Pascallanger multiprotocol module that running already with a
cc2500 (frsky d, x ans Corona protocols) and A7105 (flysky 2A protocol).
I use a a1117 for the 3,3v and 10uf /100nf capacitors.
I have a Led on A1 et simulate strap bind with à 4,7k between A3 ans gnd.
When i start my uno, the Led stay on, with or without strap.
On tx, i have define a custom (34,0) mode.
If i launch a bind, the receiver's led stay on.
Do you think that my issue is my uno board (no A6 and A7)?

I use this schematic but without 1n4007 diode and without resistor on d2
pin.

Thanks for your help.

Pierre

**Comment by soligen2010** [comment] 2018-12-19 12:19
If it has never been bound it will always boot into bind mode even regardless of the state of A3.  Did you get it to successfully bind?  The LED should blink when the bind is complete.  If it never blinked, then there is no bind and it just keeps re-booting into bind mode,

**Comment by pierrotm777** [comment] 2018-12-19 16:40
I see that the schematic that use only one nrf24l01 has the ce pin
connected to d10 and not to 3,3v. Do you think that i  must to connect d10
pin to ce ?

**Comment by soligen2010** [comment] 2018-12-19 21:03
No, I don't think it is any of those things you suggested.  I think you maybe never bound the receiver. Did you get the successful bind indicated by the blinking LED or not?

**Comment by pierrotm777** [comment] 2018-12-19 21:04
No bind and no blink for now.

**Comment by pierrotm777** [comment] 2018-12-21 09:00
Hello,
I have tested the New board definition and now I can compile without error.
But i can't bind my radio with the receiver. The serial Windows return well
that sync is waiting, but the Led stay always on.
Just one question.
I use my uno board with several project and my EEprom isn't empty. Do you
think I need to clear it before ?

**Comment by pierrotm777** [comment] 2018-12-21 09:05
Other little question, can you explain me what is the utility of d1 and d2
(1n4004)?
It's important or I can not use them ?

**Comment by soligen2010** [comment] 2018-12-21 18:17
Hear are things to do next.

In the first few lines of the serial output it displays if the primary and/or secondary radio is detected. What do these lines indicate?

If the primary radio is detected, and if you used a diode in the IRQ it is oriented correctly (the diode is only needed for 2 radios), the the fault is probably in the TX side.  Share more details on the TX module.  What hardware, what compile options.  You have to be sure this protocol is compiled in.  I have only tested with my fork of the multi-protocol code, so you could try to use the fork under soligen2010.  I dont know if the protocol works on the 32bit versions (like the iRange) as I don't have one to test with.

If you have just one radio with CSN on D14 (aka A0), the the CE pin can be tied to either D10 or +3.3,  it should not make a difference, but feel free to try both if you like.

EEPROM does not need to be erased.  The LED on indicates bind mode, so your old EEPROM data will be over-written when bind is successful.  If LED doesn't turn on, then erasing EEPROM is a way to get into bind mode without needing a button.

D1 & D2 are flyback diodes to protect against possible reverse voltage spikes.  Inductors (motors/servos) can generate these spikes.  If you have no servos or motors connected, they are optional.

Also, you can try removing the level shifters.  The NRF24L01 is 5V tolerant so they are not needed.  If the shifters are not bi-directional, then they would not work.

**Comment by pierrotm777** [comment] 2018-12-21 19:25
Thanks for your help again,
I use only one nrf24l01 but i think to use two when the receiver will run.
My connections are:
Irq=A2
Sck=D13
Csn=A0
+5v
Gnd
Mosi=D11
Miso=D12
I have a 1n4148 on irq signal.
The Led is always on and nerver blink when i try to bind.
I send you my config file.
I have build a multiprotocol module with a pro mini. It run very well with
cc2500 and A7105. I have tested a nrf24l01 with the E-Sky protocol. My
receiver E-Sky 000731 receive well bind command(receiver led blink) but
bind isn't ok.
It's why I try with your diy project that i have found after my first test.
My transmitter is also a diy based on OpenAVRc project. I have build the
board for this project. I think build a board for two nrf24l01 for you with
kicad.
I use a custom protocol (34,0).
I don't remember what serial return. I said you that as soon as possible.

**Comment by pierrotm777** [comment] 2018-12-21 19:46
I use this module on my transmitter, but a I have also tested another
nrf24l01 without pa lna in the transmitter.
€ 3,80  16� réduction | E01-ML01DP5 Longue Portée SPI nRF24L01P 2.4 ghz 100
mw SMA Antenne IoT Sans Fil Émetteur-Récepteur Émetteur Récepteur nRF24L01P
RF Module
https://s.click.aliexpress.com/e/bDCRjd8l

**Comment by soligen2010** [comment] 2019-01-21 19:40
It has been a month and no new information as been posted on the recommended next steps for this, so closing the issue.  Re-open it if you get more details to share.

**Closed as completed by soligen2010** 2019-01-21 19:40 UTC

**Comment by pierrotm777** [comment] 2019-01-22 13:32
Sorry,
I wait a new nrf24l01 with pa lna feature for a new test. 
I have done my test with an Uno board and not a pro mini. So I and I don't know if use an Uno with your code is a good idea

**Comment by soligen2010** [comment] 2019-01-22 18:14
Neither of those things should make a difference
